import argparse
from pathlib import Path

import torch
import yaml
from torch.utils.data import DataLoader
from tqdm import tqdm

from vq_memory import JointStateVQVAE, JointWindowDataset, kmeans_codebook


def build_model(cfg):
    return JointStateVQVAE(
        joint_dim=cfg["joint_dim"],
        window_size=cfg["window_size"],
        hidden_dim=cfg["hidden_dim"],
        latent_dim=cfg["latent_dim"],
        codebook_size=cfg["codebook_size"],
        commitment_cost=cfg["commitment_cost"],
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/vq_memory.yaml")
    parser.add_argument("--data", default=None, help="NPZ trajectory dataset generated by data_generation.collect_symbolic_demos")
    parser.add_argument("--output-dir", default="artifacts/vq_memory")
    parser.add_argument("--steps", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    with open(args.config, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    torch.manual_seed(int(cfg.get("seed", 42)))
    model = build_model(cfg)

    if args.dry_run:
        x = torch.randn(8, cfg["window_size"], cfg["joint_dim"])
        out = model(x)
        centroids, assignment = kmeans_codebook(model.quantizer.embedding.weight, cfg["cluster_size"])
        print("dry_run_ok", "loss", round(float(out["loss"]), 6), "centroids", tuple(centroids.shape), "assignment", tuple(assignment.shape))
        return

    if args.data is None:
        raise ValueError("--data is required unless --dry-run is used")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    dataset = JointWindowDataset(args.data, window_size=cfg["window_size"], stride=cfg["stride"])
    batch_size = int(args.batch_size or cfg["batch_size"])
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=False, num_workers=0)
    model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=float(cfg["learning_rate"]))
    max_steps = int(args.steps or cfg["max_steps"])

    model.train()
    step = 0
    last = {}
    progress = tqdm(total=max_steps, desc="train_vqvae")
    while step < max_steps:
        for batch in loader:
            batch = batch.to(device)
            out = model(batch)
            opt.zero_grad(set_to_none=True)
            out["loss"].backward()
            opt.step()
            step += 1
            last = {k: float(v.detach().cpu()) for k, v in out.items() if k.endswith("loss") or k == "loss"}
            progress.set_postfix({k: f"{v:.4f}" for k, v in last.items()})
            progress.update(1)
            if step >= max_steps:
                break
    progress.close()

    model.eval()
    with torch.no_grad():
        codebook = model.quantizer.embedding.weight.detach().cpu()
        centroids, assignment = kmeans_codebook(codebook, cfg["cluster_size"], seed=int(cfg.get("seed", 42)))

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "model_state_dict": model.cpu().state_dict(),
            "config": cfg,
            "codebook": codebook,
            "cluster_centroids": centroids.cpu(),
            "code_to_cluster": assignment.cpu(),
            "last_losses": last,
            "dataset": str(args.data),
            "steps": step,
            "num_windows": len(dataset),
        },
        output_dir / "vq_memory_tokenizer.pt",
    )
    with open(output_dir / "config.yaml", "w", encoding="utf-8") as f:
        yaml.safe_dump(cfg, f, sort_keys=False)
    print("saved", output_dir / "vq_memory_tokenizer.pt")
    print("steps", step, "num_windows", len(dataset), "last_losses", last)


if __name__ == "__main__":
    main()
